### ISSUE TITLE
项目还是报错

### ISSUE THREAD

**Issue by MaZhiJun** [jiangdongguo/OpenCV4Android#3]
Process: com.jiangdg.opencv4android, PID: 20802
    java.lang.RuntimeException: Unable to resume activity {com.jiangdg.opencv4android/com.jiangdg.opencv4android.imgproc.ImageSmoothActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
    ]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3132)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
        at android.app.ActivityThread.access$900(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:1896)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity$1.onManagerConnected(ImageSmoothActivity.java:54)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity.onResume(ImageSmoothActivity.java:97)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
        at android.app.Activity.performResume(Activity.java:6446)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3122)
        	... 10 more

**Comment by MaZhiJun** [comment]
帮忙在看看

**Comment by jessezhaordmp** [comment]
I have similar error, maybe need to fix by ourselves 😄
